# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = ""
  weight = 10

[[main]]
  name = "Staff"
  identifier = "staff"
  url = "/staff/"
  weight = 20

[[main]]
  name = "Theophile Bigirumurame"
  parent = "staff"
  url = "/staff/theophile_bigirumurame/"
  weight = 21

[[main]]
  name = "Andy Bryant"
  parent = "staff"
  url = "/staff/andy_bryant/"
  weight = 22

[[main]]
  name = "Thomas Chadwick"
  parent = "staff"
  url = "/staff/thomas_chadwick/"
  weight = 23

[[main]]
  name = "Svetlana Cherlin"
  parent = "staff"
  url = "/staff/svetlana_cherlin/"
  weight = 24

[[main]]
  name = "Mike Cole"
  parent = "staff"
  url = "/staff/mike_cole/"
  weight = 25

[[main]]
  name = "Holly Fisher"
  parent = "staff"
  url = "/staff/holly_fisher/"
  weight = 26

[[main]]
  name = "Tony Fouweather"
  parent = "staff"
  url = "/staff/tony_fouweather/"
  weight = 27

[[main]]
  name = "Michael Grayling"
  parent = "staff"
  url = "/staff/michael_grayling/"
  weight = 28

[[main]]
  name = "Shaun Hiu"
  parent = "staff"
  url = "/staff/shaun_hiu/"
  weight = 29

[[main]]
  name = "Valentina Mamasoula"
  parent = "staff"
  url = "/staff/valentina_mamasoula/"
  weight = 30

[[main]]
  name = "John Matthews"
  parent = "staff"
  url = "/staff/john_matthews/"
  weight = 31

[[main]]
  name = "Helen Mossop"
  parent = "staff"
  url = "/staff/helen_mossop/"
  weight = 32

[[main]]
  name = "Jérémie Nsengimana"
  parent = "staff"
  url = "/staff/jeremie_nsengimana/"
  weight = 33

[[main]]
  name = "Vicky Ryan"
  parent = "staff"
  url = "/staff/vicky_ryan/"
  weight = 34

[[main]]
  name = "Dawn Teare"
  parent = "staff"
  url = "/staff/dawn_teare/"
  weight = 35

[[main]]
  name = "James Wason"
  parent = "staff"
  url = "/staff/james_wason/"
  weight = 36

[[main]]
  name = "Faye Williamson"
  parent = "staff"
  url = "/staff/faye_williamson/"
  weight = 37

[[main]]
  name = "Nina Wilson"
  parent = "staff"
  url = "/staff/nina_wilson/"
  weight = 38

[[main]]
  name = "Haiyan Zheng"
  parent = "staff"
  url = "/staff/haiyan_zheng/"
  weight = 39

[[main]]
  name = "PhD students"
  identifier = "phd_students"
  url = "/phd_students/"
  weight = 50

[[main]]
  name = "Ruqayya Azher"
  parent = "phd_students"
  url = "/phd_students/ruqayya_azher/"
  weight = 51

[[main]]
  name = "Aritra Mukherjee"
  parent = "phd_students"
  url = "/phd_students/aritra_mukherjee/"
  weight = 52

[[main]]
  name = "Luke Ouma"
  parent = "phd_students"
  url = "/phd_students/luke_ouma/"
  weight = 53

[[main]]
  name = "Samuel Sarkodie"
  parent = "phd_students"
  url = "/phd_students/samuel_sarkodie/"
  weight = 54

[[main]]
  name = "Lou Whitehead"
  parent = "phd_students"
  url = "/phd_students/lou_whitehead/"
  weight = 55

[[main]]
  name = "Methodology research"
  identifier = "methodology_research"
  url = "/methodology_research/"
  weight = 45

[[main]]
  name = "Overview"
  parent = "methodology_research"
  url = "/methodology_research/overview/"
  weight = 50

[[main]]
  name = "Adaptive designs"
  parent = "methodology_research"
  url = "/methodology_research/adaptive_designs/"
  weight = 51

[[main]]
  name = "Projects"
  identifier = "projects"
  url = "/projects/"
  weight = 60

[[main]]
  name = "Publications"
  url = "/publications/"
  weight = 70

[[main]]
  name = "News"
  url = "/news/"
  weight = 80

[[main]]
  name = "Contact"
  url = "/contact/"
  weight = 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
