# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = ""
  weight = 10

[[main]]
  name = "People"
  identifier = "people"
  url = "/people/"
  weight = 20

[[main]]
  name = "Theophile Bigirumurame"
  parent = "people"
  url = "/people/theophile_bigirumurame/"
  weight = 21

[[main]]
  name = "Andy Bryant"
  parent = "people"
  url = "/people/andy_bryant/"
  weight = 22

[[main]]
  name = "Thomas Chadwick"
  parent = "people"
  url = "/people/thomas_chadwick/"
  weight = 23

[[main]]
  name = "Svetlana Cherlin"
  parent = "people"
  url = "/people/svetlana_cherlin/"
  weight = 24

[[main]]
  name = "Mike Cole"
  parent = "people"
  url = "/people/mike_cole/"
  weight = 25

[[main]]
  name = "Holly Fisher"
  parent = "people"
  url = "/people/holly_fisher/"
  weight = 26

[[main]]
  name = "Tony Fouweather"
  parent = "people"
  url = "/people/tony_fouweather/"
  weight = 27

[[main]]
  name = "Michael Grayling"
  parent = "people"
  url = "/people/michael_grayling/"
  weight = 28

[[main]]
  name = "Shaun Hiu"
  parent = "people"
  url = "/people/shaun_hiu/"
  weight = 29

[[main]]
  name = "Valentina Mamasoula"
  parent = "people"
  url = "/people/valentina_mamasoula/"
  weight = 30

[[main]]
  name = "John Matthews"
  parent = "people"
  url = "/people/john_matthews/"
  weight = 31

[[main]]
  name = "Helen Mossop"
  parent = "people"
  url = "/people/helen_mossop/"
  weight = 32

[[main]]
  name = "Jérémie Nsengimana"
  parent = "people"
  url = "/people/jeremie_nsengimana/"
  weight = 33

[[main]]
  name = "Luke Ouma"
  parent = "people"
  url = "/people/luke_ouma/"
  weight = 34

[[main]]
  name = "Vicky Ryan"
  parent = "people"
  url = "/people/vicky_ryan/"
  weight = 35

[[main]]
  name = "Dawn Teare"
  parent = "people"
  url = "/people/dawn_teare/"
  weight = 36

[[main]]
  name = "James Wason"
  parent = "people"
  url = "/people/james_wason/"
  weight = 37

[[main]]
  name = "Nina Wilson"
  parent = "people"
  url = "/people/nina_wilson/"
  weight = 38

[[main]]
  name = "Haiyan Zheng"
  parent = "people"
  url = "/people/haiyan_zheng/"
  weight = 39

[[main]]
  name = "Methodology research"
  identifier = "methodology_research"
  url = "/methodology_research/"
  weight = 40

[[main]]
  name = "Overview"
  parent = "methodology_research"
  url = "/methodology_research/overview/"
  weight = 41

[[main]]
  name = "Adaptive designs"
  parent = "methodology_research"
  url = "/methodology_research/adaptive_designs/"
  weight = 42

[[main]]
  name = "Projects"
  identifier = "projects"
  url = "/projects/"
  weight = 50

[[main]]
  name = "Publications"
  url = "/publications/"
  weight = 60

[[main]]
  name = "News"
  url = "/news/"
  weight = 70

[[main]]
  name = "Contact"
  url = "/contact/"
  weight = 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
